import { FormEvent, useState } from "react";
import type { RunnerApplication } from "../lib/contracts";

interface ApplicationViewProps {
  onApply: (input: { name: string; age_confirmed: boolean; transport: string; service_radius_miles: number }) => Promise<RunnerApplication>;
  onApprove: (id: string) => Promise<RunnerApplication>;
}

export function ApplicationView({ onApply, onApprove }: ApplicationViewProps) {
  const [name, setName] = useState("Taylor Morgan"); const [age, setAge] = useState(false); const [transport, setTransport] = useState("bike"); const [radius, setRadius] = useState(8); const [application, setApplication] = useState<RunnerApplication | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { setApplication(await onApply({ name, age_confirmed: age, transport, service_radius_miles: radius })); } catch (value) { setError(value instanceof Error ? value.message : "Application failed"); } finally { setBusy(false); } };
  const approve = async () => { if (!application) return; setBusy(true); try { setApplication(await onApprove(application.id)); } finally { setBusy(false); } };
  return <main className="application-page"><section className="application-story"><p className="eyebrow">FLEXIBLE LOCAL WORK</p><h1>Move your day forward.</h1><p>Choose nearby tasks, see your pay before accepting, and decide when you work. BSR Runner is designed to expand access to dignified, flexible earning opportunities.</p><div className="benefit-list"><div><span>01</span><strong>No fixed shifts</strong><p>Go online when you want and accept only the jobs that fit.</p></div><div><span>02</span><strong>Fair automatic pay</strong><p>Distance, time, weight and urgency are calculated before you accept.</p></div><div><span>03</span><strong>Protected completion</strong><p>Every state change is recorded and payouts release after confirmation.</p></div></div><div className="legal-note"><strong>Independent-work demo</strong><p>Production launch requires legal review of worker classification, insurance, taxes and local delivery rules.</p></div></section><section className="application-card">{application ? <div className="application-result"><span className={application.status === "approved" ? "approval-icon approved" : "approval-icon"}>{application.status === "approved" ? "✓" : "…"}</span><p className="eyebrow">APPLICATION {application.status}</p><h2>{application.status === "approved" ? "You are ready to run." : "Demo review received."}</h2><p>{application.status === "approved" ? "Browse the job market and accept work near you." : "A production review would verify identity and screening. This classroom version simulates approval."}</p>{application.status === "pending" && <button className="primary wide" disabled={busy} onClick={approve}>Approve fictional demo application</button>}</div> : <form onSubmit={submit}><p className="eyebrow">RUNNER APPLICATION</p><h2>Tell us how you move</h2><label>Full name<input required value={name} onChange={(e) => setName(e.target.value)}/></label><label>Transportation<select value={transport} onChange={(e) => setTransport(e.target.value)}><option value="bike">Bicycle</option><option value="car">Car</option><option value="walking">Walking</option><option value="scooter">Scooter</option></select></label><label>Service radius: <strong>{radius} miles</strong><input type="range" min="1" max="25" value={radius} onChange={(e) => setRadius(Number(e.target.value))}/></label><label className="check-row"><input type="checkbox" checked={age} onChange={(e) => setAge(e.target.checked)}/><span>I confirm that I am at least 18 years old and agree to the safety rules.</span></label><div className="fictional-notice">No real ID, Social Security number or background-check data is collected in this demo.</div>{error && <p className="form-error">{error}</p>}<button className="primary wide" disabled={!age || busy}>{busy ? "Submitting…" : "Submit demo application →"}</button></form>}</section></main>;
}
