import type { AdminSummary, RunnerApplication, RunnerEarnings, RunnerTask } from "../lib/contracts";
import { money } from "../lib/contracts";

export function EarningsView({ earnings, tasks }: { earnings: RunnerEarnings | null; tasks: RunnerTask[] }) {
  const completed = tasks.filter((task) => task.state === "completed");
  return <main className="dashboard-page"><div className="page-intro"><p className="eyebrow">RUNNER WALLET</p><h1>Your work, clearly counted.</h1><p>Demo payouts release only after a valid customer completion code.</p></div><div className="earnings-grid"><article className="balance-card"><small>Available demo balance</small><strong>{money(earnings?.available_cents ?? 0)}</strong><p>Ready after protected completion</p></article><article><small>Completed tasks</small><strong>{earnings?.completed_tasks ?? 0}</strong><p>All-time fictional total</p></article><article><small>This week</small><strong>{money(earnings?.available_cents ?? 0)}</strong><p>No fees hidden from runners</p></article></div><section className="dashboard-table"><div className="section-heading"><h2>Recent earnings</h2><span>Personal · USD</span></div>{completed.length ? completed.map((task) => <div className="table-row" key={task.id}><span className="category-icon">✓</span><div><strong>{task.title}</strong><small>{task.pickup_area} → {task.dropoff_area}</small></div><span className="state completed">completed</span><strong>{money(task.runner_payout_cents)}</strong></div>) : <div className="empty-table"><span>↗</span><p>Complete the seeded package task to see a payout here.</p></div>}</section></main>;
}

export function AdminView({ summary, applications, tasks, onApprove }: { summary: AdminSummary | null; applications: RunnerApplication[]; tasks: RunnerTask[]; onApprove: (id: string) => void }) {
  const cards = [["Active tasks", summary?.active_tasks ?? 0], ["Approved runners", summary?.approved_runners ?? 0], ["Pending reviews", summary?.pending_applications ?? 0], ["Unsafe tasks blocked", summary?.prohibited_tasks_blocked ?? 0]];
  return <main className="dashboard-page admin-page"><div className="page-intro"><p className="eyebrow">ADMIN SAFETY DESK</p><h1>Trust is an operating system.</h1><p>Monitor fictional applications, task states, reports and prohibited-task defenses.</p></div><div className="admin-stats">{cards.map(([label, value]) => <article key={label}><small>{label}</small><strong>{value}</strong></article>)}</div><div className="admin-columns"><section className="dashboard-table"><div className="section-heading"><h2>Runner applications</h2><span>{applications.length} total</span></div>{applications.map((application) => <div className="table-row" key={application.id}><span className="category-icon">{application.transport === "bike" ? "🚲" : "🚗"}</span><div><strong>{application.name}</strong><small>{application.transport} · {application.service_radius_miles} mile radius · 18+ confirmed</small></div><span className={`state ${application.status}`}>{application.status}</span>{application.status === "pending" && <button className="mini-button" onClick={() => onApprove(application.id)}>Approve demo</button>}</div>)}</section><section className="dashboard-table"><div className="section-heading"><h2>Task activity</h2><span>{tasks.length} total</span></div>{tasks.slice(0, 5).map((task) => <div className="table-row compact" key={task.id}><div><strong>{task.title}</strong><small>{task.pickup_area} → {task.dropoff_area}</small></div><span className={`state ${task.state}`}>{task.state.replaceAll("_", " ")}</span></div>)}</section></div></main>;
}
